import { Column, Entity, Index } from 'typeorm';
import { TimeStampEntity } from 'src/core/database/entities/time-stamp.entity';

/**
 * One planned bot content item for a given day. Drives generation, quota and
 * the Telegram digest. It is NOT the source of truth for what is live — that is
 * the `posts` table. The plan links loosely to the produced post (best-effort,
 * FIFO) purely for the digest; correctness (quota, publishing, digest counts)
 * never depends on that link being exact.
 */
export type ContentBotPlanStatus =
  | 'planned' // row created, not yet generated
  | 'generating' // enqueued for generation (taskId set)
  | 'generated' // draft post produced, awaiting publish
  | 'published' // pushed to the public feed
  | 'failed'; // generation charge refunded / gave up

export type ContentBotMediaKind = 'image' | 'video';

@Entity('content_bot_plan')
@Index('IDX_content_bot_plan_status', ['status'])
@Index('IDX_content_bot_plan_plan_date', ['planDate'])
@Index('IDX_content_bot_plan_tag', ['tagId'])
export class ContentBotPlanEntity extends TimeStampEntity {
  /** Calendar day this item belongs to (YYYY-MM-DD, server local). */
  @Column({ type: 'date' })
  planDate: string;

  @Column({ type: 'varchar', length: 20 })
  mediaKind: ContentBotMediaKind;

  @Column({ type: 'varchar', length: 80, nullable: true })
  aiService: string | null;

  @Column({ type: 'int', nullable: true })
  tagId: number | null;

  @Column({ type: 'varchar', length: 120, nullable: true })
  promptTemplateKey: string | null;

  @Column({ type: 'text', nullable: true })
  promptText: string | null;

  @Column({ type: 'text', nullable: true })
  negativePrompt: string | null;

  /** Fits in a signed int32 (see randomVideoSeed). */
  @Column({ type: 'int', nullable: true })
  seed: number | null;

  @Column({ type: 'varchar', length: 20, default: 'planned' })
  status: ContentBotPlanStatus;

  /**
   * Preview rows are generated by the admin preview endpoint for review only.
   * The publisher NEVER auto-publishes them, so previewing never leaks drafts
   * into the live feed even after the bot is enabled the same day.
   */
  @Column({ type: 'boolean', default: false })
  isPreview: boolean;

  /** BullMQ job id / generation taskId from the enqueue call. */
  @Column({ type: 'varchar', length: 64, nullable: true })
  taskId: string | null;

  /** Produced post id (best-effort link, set at publish time). */
  @Column({ type: 'int', nullable: true })
  postId: number | null;

  /** Optional reason when status = 'failed'. */
  @Column({ type: 'varchar', length: 255, nullable: true })
  failureReason: string | null;
}
