version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: yallery-db
    environment:
      MYSQL_ROOT_PASSWORD: devpass
      MYSQL_DATABASE: y-app
      MYSQL_PASSWORD: devpass
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - '3306:3306'

volumes:
  db-data:
  redis-data:
