import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateMediaTextVideoWorkflows1785300000000
  implements MigrationInterface
{
  name = 'CreateMediaTextVideoWorkflows1785300000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE \`media_text_video_workflows\` (
        \`id\` int NOT NULL AUTO_INCREMENT,
        \`taskId\` varchar(64) NOT NULL,
        \`userId\` int NOT NULL,
        \`chargeId\` varchar(64) NOT NULL,
        \`contestSubmissionId\` int NULL,
        \`pipelineMode\` varchar(16) NOT NULL,
        \`pipelineConfigVersion\` varchar(128) NOT NULL,
        \`prunaClientPolicySha256\` char(64) NOT NULL,
        \`promptCompilerVersion\` varchar(128) NOT NULL,
        \`stillQcPolicyVersion\` varchar(128) NOT NULL,
        \`videoQcPolicyVersion\` varchar(128) NOT NULL,
        \`cascadeRunpodEndpointId\` varchar(128) NOT NULL,
        \`cascadeRunpodApiKeyConfigKey\` varchar(128) NOT NULL,
        \`artifactTtlMs\` int UNSIGNED NOT NULL,
        \`stillPollIntervalMs\` int UNSIGNED NOT NULL,
        \`stillTotalTimeoutMs\` int UNSIGNED NOT NULL,
        \`i2vPollIntervalMs\` int UNSIGNED NOT NULL,
        \`i2vTotalTimeoutMs\` int UNSIGNED NOT NULL,
        \`rawPromptSha256\` char(64) NOT NULL,
        \`stillPromptSha256\` char(64) NOT NULL,
        \`motionPromptSha256\` char(64) NOT NULL,
        \`width\` smallint UNSIGNED NOT NULL,
        \`height\` smallint UNSIGNED NOT NULL,
        \`frames\` smallint UNSIGNED NOT NULL,
        \`fps\` smallint UNSIGNED NOT NULL DEFAULT 24,
        \`stillSeed\` int UNSIGNED NOT NULL,
        \`videoSeed\` int UNSIGNED NOT NULL,
        \`stillProvider\` varchar(32) NULL,
        \`stillModel\` varchar(32) NULL,
        \`state\` varchar(40) NOT NULL DEFAULT 'QUEUED',
        \`version\` int UNSIGNED NOT NULL DEFAULT 0,
        \`terminalReasonCode\` varchar(80) NULL,
        \`refundStatus\` varchar(16) NOT NULL DEFAULT 'none',
        \`refundCompletedAt\` timestamp(6) NULL,
        \`submissionAttemptId\` char(36) NULL,
        \`stillRequestSha256\` char(64) NULL,
        \`stillPostDispatchClaimedAt\` timestamp(6) NULL,
        \`providerPredictionId\` varchar(128) NULL,
        \`stillSubmissionAcceptedAt\` timestamp(6) NULL,
        \`stillReadyAt\` timestamp(6) NULL,
        \`sourceMime\` varchar(32) NULL,
        \`sourceByteLength\` int UNSIGNED NULL,
        \`sourceSha256\` char(64) NULL,
        \`canonicalMime\` varchar(32) NULL,
        \`canonicalByteLength\` int UNSIGNED NULL,
        \`canonicalSha256\` char(64) NULL,
        \`decodedRgbSha256\` char(64) NULL,
        \`privateArtifactRef\` varchar(256) NULL,
        \`artifactDeleteAfter\` timestamp(6) NULL,
        \`stillCanonicalizedAt\` timestamp(6) NULL,
        \`stillQcDecision\` varchar(16) NULL,
        \`stillQcReasonCode\` varchar(80) NULL,
        \`stillQcCompletedAt\` timestamp(6) NULL,
        \`i2vRequestSha256\` char(64) NULL,
        \`i2vDispatchClaimedAt\` timestamp(6) NULL,
        \`runpodJobId\` varchar(128) NULL,
        \`i2vAcceptedAt\` timestamp(6) NULL,
        \`videoArtifactSha256\` char(64) NULL,
        \`videoPrivateArtifactRef\` varchar(256) NULL,
        \`videoArtifactByteLength\` int UNSIGNED NULL,
        \`videoWidth\` smallint UNSIGNED NULL,
        \`videoHeight\` smallint UNSIGNED NULL,
        \`videoHasAudio\` boolean NULL,
        \`videoArtifactDeleteAfter\` timestamp(6) NULL,
        \`videoReadyAt\` timestamp(6) NULL,
        \`videoQcDecision\` varchar(16) NULL,
        \`videoQcReasonCode\` varchar(80) NULL,
        \`videoQcCompletedAt\` timestamp(6) NULL,
        \`finalPostId\` int NULL,
        \`finalizingAt\` timestamp(6) NULL,
        \`completedAt\` timestamp(6) NULL,
        \`failedAt\` timestamp(6) NULL,
        \`artifactCleanupStatus\` varchar(16) NOT NULL DEFAULT 'not_required',
        \`artifactCleanupAfter\` timestamp(6) NULL,
        \`artifactCleanupClaimedAt\` timestamp(6) NULL,
        \`artifactCleanupCompletedAt\` timestamp(6) NULL,
        \`stillSubmitDurationMs\` int UNSIGNED NULL,
        \`stillPollDurationMs\` int UNSIGNED NULL,
        \`stillDownloadDurationMs\` int UNSIGNED NULL,
        \`stillCanonicalizeDurationMs\` int UNSIGNED NULL,
        \`stillQcDurationMs\` int UNSIGNED NULL,
        \`i2vDurationMs\` int UNSIGNED NULL,
        \`videoQcDurationMs\` int UNSIGNED NULL,
        \`totalDurationMs\` int UNSIGNED NULL,
        \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
        \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
        UNIQUE INDEX \`IDX_media_text_video_workflows_task_id\` (\`taskId\`),
        UNIQUE INDEX \`IDX_media_text_video_workflows_prediction_id\` (\`providerPredictionId\`),
        UNIQUE INDEX \`IDX_media_text_video_workflows_runpod_job_id\` (\`runpodJobId\`),
        UNIQUE INDEX \`IDX_media_text_video_workflows_final_post_id\` (\`finalPostId\`),
        INDEX \`IDX_media_text_video_workflows_state_updated\` (\`state\`, \`updatedAt\`),
        INDEX \`IDX_media_text_video_workflows_user_created\` (\`userId\`, \`createdAt\`),
        INDEX \`IDX_media_text_video_workflows_refund_state\` (\`refundStatus\`, \`state\`),
        INDEX \`IDX_media_text_video_workflows_cleanup_due\` (\`artifactCleanupStatus\`, \`artifactCleanupAfter\`),
        INDEX \`IDX_media_text_video_workflows_cleanup_claim\` (\`artifactCleanupStatus\`, \`artifactCleanupClaimedAt\`),
        PRIMARY KEY (\`id\`)
      ) ENGINE=InnoDB
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('DROP TABLE `media_text_video_workflows`');
  }
}
