export enum RewardTypeEnum {
  DAILY_REWARD = 'DAILY_REWARD',
  LIKE_EARN = 'LIKE_EARN',
  LIKE_SPEND = 'LIKE_SPEND',
  SHARE_REWARD = 'SHARE_REWARD',
  SHARE_YEPS = 'SHARE_YEPS',
  PAYMENT_5000 = 'PAYMENT_5000',
  PAYMENT_15000 = 'PAYMENT_15000',
  PAYMENT_30000 = 'PAYMENT_30000',
  REFERRAL_REWARD = 'REFERRAL_REWARD',
  REGISTRATION_BONUS = 'REGISTRATION_BONUS',
}
